from BaseClasses import ItemClassification


from .constants import *


core_rooms = {
    "Antechamber": {
        ROOM_ITEM_ID_KEY: 45,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: [],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Room 46": {
        ROOM_ITEM_ID_KEY: 46,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Entrance Hall": {
        ROOM_ITEM_ID_KEY: 2,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 2,  # EXCEPTION: REQUIRES OBSERVATORY
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: [],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

classroom_positions = [
    "CENTER - Tier 1 G",
    "FRONT - Tier 1 G",
    "CORNER - Tier 1 G",
    "EDGE ADVANCE WESTWING - G",
    "EDGE ADVANCE EASTWING - G",
    "EDGE RETREAT WESTWING -  G",
    "EDGE RETREAT EASTTWING -  G",
    "EDGEPIERCE G",
]

classrooms = {
    "Classroom 1": {
        ROOM_ITEM_ID_KEY: 101,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 2": {
        ROOM_ITEM_ID_KEY: 102,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 3": {
        ROOM_ITEM_ID_KEY: 103,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 4": {
        ROOM_ITEM_ID_KEY: 104,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 5": {
        ROOM_ITEM_ID_KEY: 105,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 6": {
        ROOM_ITEM_ID_KEY: 106,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 7": {
        ROOM_ITEM_ID_KEY: 107,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom 8": {
        ROOM_ITEM_ID_KEY: 108,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Classroom Exam": {
        ROOM_ITEM_ID_KEY: 109,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: classroom_positions,
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

secret_blue = {
    "Dovecote": {
        ROOM_ITEM_ID_KEY: 201,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: ["EDGEPIERCE EAST", "EDGEPIERCE WEST", "NORTH PIERCE", "CENTER - Tier 2"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "The Kennel": {
        ROOM_ITEM_ID_KEY: 202,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONT - Tier 1", "EDGECREEP EAST", "EDGECREEP WEST", "CENTER - Tier 1"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Clock Tower": {
        ROOM_ITEM_ID_KEY: 203,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "CENTER - Tier 2 G",
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_ROOK,
    },
    "Planetarium": {
        ROOM_ITEM_ID_KEY: 204,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "CENTER - Tier 2",
            "FRONT - Tier 1",
            "CORNER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
            "NORTH PIERCE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Mechanarium": {
        ROOM_ITEM_ID_KEY: 205,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,  # This is the most restrictive state of the mechanarium.
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Toolshed": {
        ROOM_ITEM_ID_KEY: 206,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Shelter": {
        ROOM_ITEM_ID_KEY: 207,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Schoolhouse": {
        ROOM_ITEM_ID_KEY: 208,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Shrine": {
        ROOM_ITEM_ID_KEY: 209,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
} | classrooms


blue_001_012 = {
    "The Foundation": {
        ROOM_ITEM_ID_KEY: 1,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 1", "CENTER - Tier 2", "CENTER - Tier 3"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Spare Room": {
        ROOM_ITEM_ID_KEY: 3,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,  # Technically has SOME SOMETIMES, but not for all upgrades.
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK - RARE", "CENTER - Tier 1", "EDGECREEP EAST", "EDGECREEP WEST"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Rotunda": {
        ROOM_ITEM_ID_KEY: 4,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2 G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Parlor": {
        ROOM_ITEM_ID_KEY: 5,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Billiard Room": {
        ROOM_ITEM_ID_KEY: 6,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 2",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Gallery": {
        ROOM_ITEM_ID_KEY: 7,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK - RARE", "CENTER - Tier 3", "EDGECREEP - RARE"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Room 8": {
        ROOM_ITEM_ID_KEY: 8,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: ["DOWSING NOMBOS"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Closet": {
        ROOM_ITEM_ID_KEY: 9,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Walk-In Closet": {
        ROOM_ITEM_ID_KEY: 10,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "CENTER - Tier 2 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Attic": {
        ROOM_ITEM_ID_KEY: 11,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_BISHOP,
    },
    "Storeroom": {
        ROOM_ITEM_ID_KEY: 12,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
}
blue_013_024 = {
    "Nook": {
        ROOM_ITEM_ID_KEY: 13,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_ROOK,
    },
    "Garage": {
        ROOM_ITEM_ID_KEY: 14,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["EDGE ADVANCE WESTWING - G", "EDGEPIERCE G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Music Room": {
        ROOM_ITEM_ID_KEY: 15,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Locker Room": {
        ROOM_ITEM_ID_KEY: 16,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONT - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING - G",
            "EDGE RETREAT EASTWING - G",
            "CENTER - Tier 2 G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Den": {
        ROOM_ITEM_ID_KEY: 17,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Wine Cellar": {
        ROOM_ITEM_ID_KEY: 18,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 1",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Trophy Room": {
        ROOM_ITEM_ID_KEY: 19,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Ballroom": {
        ROOM_ITEM_ID_KEY: 20,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK G - RARE", "CENTER - Tier 2 G", "EDGECREEP - RARE G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Pantry": {
        ROOM_ITEM_ID_KEY: 21,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Rumpus Room": {
        ROOM_ITEM_ID_KEY: 22,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "CENTER - Tier 2 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_BISHOP,
    },
    "Vault": {
        ROOM_ITEM_ID_KEY: 23,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 2 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_ROOK,
    },
    "Office": {
        ROOM_ITEM_ID_KEY: 24,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 2 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_KING,
    },
}
blue_025_036 = {
    "Drawing Room": {
        ROOM_ITEM_ID_KEY: 25,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONT - Tier 1 G",
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Study": {
        ROOM_ITEM_ID_KEY: 26,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 2",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
            "Center Rare",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_QUEEN,
    },
    "Library": {
        ROOM_ITEM_ID_KEY: 27,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 2",
            "EDGECREEP - RARE",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Chamber of Mirrors": {
        ROOM_ITEM_ID_KEY: 28,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "The Pool": {
        ROOM_ITEM_ID_KEY: 29,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,  # REQUIRES MOUNT HOLLY GIFT SHOP
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CENTER - Tier 2 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Drafting Studio": {
        ROOM_ITEM_ID_KEY: 30,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK G - RARE", "CENTER - Tier 2 G", "EDGECREEP - RARE G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Utility Closet": {
        ROOM_ITEM_ID_KEY: 31,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "CORNER - Tier 1",
            "CENTER - Tier 2",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Boiler Room": {
        ROOM_ITEM_ID_KEY: 32,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2 G", "EDGE ADVANCE EASTWING - G", "EDGE RETREAT WESTWING -  G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Pump Room": {
        ROOM_ITEM_ID_KEY: 33,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "CORNER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
            "NORTH PIERCE",
            "CENTER - Tier 2",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Security": {
        ROOM_ITEM_ID_KEY: 34,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["NORTH PIERCE G", "CENTER - Tier 1 G", "EDGEPIERCE G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_KNIGHT,
    },
    "Workshop": {
        ROOM_ITEM_ID_KEY: 35,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK - RARE", "CENTER - Tier 2", "EDGECREEP - RARE", "Center Rare"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Laboratory": {
        ROOM_ITEM_ID_KEY: 36,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}
blue_037_046 = {
    "Sauna": {
        ROOM_ITEM_ID_KEY: 37,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "CENTER - Tier 1",
            "FRONT - Tier 1",
            "CORNER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
            "NORTH PIERCE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Coat Check": {
        ROOM_ITEM_ID_KEY: 38,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Mail Room": {
        ROOM_ITEM_ID_KEY: 39,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 3",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Freezer": {
        ROOM_ITEM_ID_KEY: 40,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Dining Room": {
        ROOM_ITEM_ID_KEY: 41,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CENTER - Tier 1",
            "EDGECREEP - RARE",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Observatory": {
        ROOM_ITEM_ID_KEY: 42,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONT - Tier 1 G",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_KNIGHT,
    },
    "Conference Room": {
        ROOM_ITEM_ID_KEY: 43,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CENTER - Tier 2",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Aquarium": {
        ROOM_ITEM_ID_KEY: 44,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CENTER - Tier 2 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

blue_rooms = core_rooms | secret_blue | blue_001_012 | blue_013_024 | blue_025_036 | blue_037_046

bedrooms = {
    "Dormitory": {
        ROOM_ITEM_ID_KEY: 301,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "CORNER - Tier 1",
            "FRONTBACK - RARE",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Hovel": {
        ROOM_ITEM_ID_KEY: 302,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Bedroom": {
        ROOM_ITEM_ID_KEY: 303,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Boudoir": {
        ROOM_ITEM_ID_KEY: 304,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 2",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Guest Bedroom": {
        ROOM_ITEM_ID_KEY: 305,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Nursery": {
        ROOM_ITEM_ID_KEY: 306,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONT - Tier 1 G",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Servant's Quarters": {
        ROOM_ITEM_ID_KEY: 307,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 2 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Bunk Room": {
        ROOM_ITEM_ID_KEY: 308,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 2,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 2",
            "EDGECREEP - RARE",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Her Ladyship's Chambers": {
        ROOM_ITEM_ID_KEY: 309,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["EDGE RETREAT WESTWING -  G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_QUEEN,
    },
    "Master Bedroom": {
        ROOM_ITEM_ID_KEY: 310,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["EDGE ADVANCE EASTWING - G", "EDGE RETREAT EASTTWING -  G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

hallways = {
    "Vestibule": {
        ROOM_ITEM_ID_KEY: 401,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 1 G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Tunnel": {
        ROOM_ITEM_ID_KEY: 402,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2", "EDGECREEP EAST", "EDGECREEP WEST"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Hallway": {
        ROOM_ITEM_ID_KEY: 403,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK - RARE", "SOUTH PIERCE", "CENTER - Tier 1"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "West Wing Hall": {
        ROOM_ITEM_ID_KEY: 404,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["EDGECREEP WEST", "EDGEPIERCE WEST"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "East Wing Hall": {
        ROOM_ITEM_ID_KEY: 405,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["EDGECREEP EAST", "EDGEPIERCE EAST"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Corridor": {
        ROOM_ITEM_ID_KEY: 406,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK - RARE", "CENTER - Tier 1", "EDGECREEP EAST", "EDGECREEP WEST"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Passageway": {
        ROOM_ITEM_ID_KEY: 407,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 1 G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Secret Passage": {
        ROOM_ITEM_ID_KEY: 408,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: [
            "CENTER - Tier 2 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Foyer": {
        ROOM_ITEM_ID_KEY: 409,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: ["FRONTBACK G - RARE", "CENTER - Tier 2 G", "EDGECREEP - RARE G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Great Hall": {
        ROOM_ITEM_ID_KEY: 410,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 3"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

green_rooms = {
    "Solarium": {
        ROOM_ITEM_ID_KEY: 501,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "CORNER - RARE G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
            "NORTH PIERCE G",
            "CENTER - Tier 2 G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Conservatory": {
        ROOM_ITEM_ID_KEY: 502,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: ["CORNER - Tier 1 G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_ROOK,
    },
    "Root Cellar": {
        ROOM_ITEM_ID_KEY: 503,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Terrace": {
        ROOM_ITEM_ID_KEY: 504,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["EDGEPIERCE EAST", "EDGEPIERCE WEST"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Patio": {
        ROOM_ITEM_ID_KEY: 505,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: ["EDGE ADVANCE WESTWING - G", "EDGE RETREAT EASTTWING -  G", "EDGEPIERCE G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Courtyard": {
        ROOM_ITEM_ID_KEY: 506,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Cloister": {
        ROOM_ITEM_ID_KEY: 507,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2 G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Veranda": {
        ROOM_ITEM_ID_KEY: 508,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: [
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Greenhouse": {
        ROOM_ITEM_ID_KEY: 509,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: ["EDGE ADVANCE EASTWING - G", "EDGE RETREAT WESTWING -  G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Morning Room": {
        ROOM_ITEM_ID_KEY: 510,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Secret Garden": {
        ROOM_ITEM_ID_KEY: 511,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            # Secret garden IS NOT draftable via normal rules, but DOES require access to these rooms as part of the logic.
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

shops = {
    "Casino": {
        ROOM_ITEM_ID_KEY: 601,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "EDGEPIERCE G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "NORTH PIERCE G",
            "CENTER - Tier 1 G",
            "CORNER - Tier 1 G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Trading Post": {
        ROOM_ITEM_ID_KEY: 602,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Commissary": {
        ROOM_ITEM_ID_KEY: 603,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Kitchen": {
        ROOM_ITEM_ID_KEY: 604,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONT - Tier 1 G",
            "NORTH PIERCE G",
            "CORNER - Tier 1 G",
            "CENTER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Locksmith": {
        ROOM_ITEM_ID_KEY: 605,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Showroom": {
        ROOM_ITEM_ID_KEY: 606,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_I,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "SILVER KEY LIST 2",
            "Center Rare G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Laundry Room": {
        ROOM_ITEM_ID_KEY: 607,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK G - RARE",
            "NORTH PIERCE G",
            "CORNER - RARE G",
            "CENTER - Tier 3 G",
            "EDGECREEP - RARE G",
            "EDGEPIERCE - RARE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Bookshop": {
        ROOM_ITEM_ID_KEY: 608,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_BISHOP,
    },
    "The Armory": {
        ROOM_ITEM_ID_KEY: 609,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "CENTER - Tier 1 G",
            "CORNER - Tier 1 G",
            "EDGE ADVANCE WESTWING - G",
            "EDGE ADVANCE EASTWING - G",
            "EDGE RETREAT WESTWING -  G",
            "EDGE RETREAT EASTTWING -  G",
            "EDGEPIERCE G",
            "NORTH PIERCE G",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_KNIGHT,
    },
    "Mount Holly Gift Shop": {
        ROOM_ITEM_ID_KEY: 610,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "CENTER - Tier 2",
            "FRONT - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}
red_rooms = {
    "Lost And Found": {
        ROOM_ITEM_ID_KEY: 701,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "CORNER - Tier 1",
            "EDGECREEP WEST",
            "EDGECREEP EAST",
            "EDGEPIERCE WEST",
            "EDGEPIERCE EAST",
            "SOUTH PIERCE",
            "CENTER - Tier 2",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_PAWN,
    },
    "Closed Exhibit": {
        ROOM_ITEM_ID_KEY: 702,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "EDGEPIERCE - RARE",
            "EDGECREEP - RARE",
            "CENTER - Tier 2",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Lavatory": {
        ROOM_ITEM_ID_KEY: 703,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "SOUTH PIERCE",
            "CORNER - Tier 1",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Chapel": {
        ROOM_ITEM_ID_KEY: 704,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_BISHOP,
    },
    "Maids Chamber": {
        ROOM_ITEM_ID_KEY: 705,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 2",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Archives": {
        ROOM_ITEM_ID_KEY: 706,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 2"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Gymnasium": {
        ROOM_ITEM_ID_KEY: 707,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CENTER - Tier 1",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Darkroom": {
        ROOM_ITEM_ID_KEY: 708,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CENTER - Tier 1",
            "EDGECREEP EAST",
            "EDGECREEP WEST",
            "EDGEPIERCE EAST",
            "EDGEPIERCE WEST",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Weight Room": {
        ROOM_ITEM_ID_KEY: 709,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 1,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_X,
        ROOM_PICK_POSITIONS_KEY: ["CENTER - Tier 3", "Center Rare"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
    "Furnace": {
        ROOM_ITEM_ID_KEY: 710,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: [
            "FRONTBACK - RARE",
            "NORTH PIERCE",
            "CORNER - RARE",
            "CENTER - Tier 3",
            "EDGECREEP - RARE",
            "EDGEPIERCE - RARE",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}
black_rooms = {
    "Treasure Trove": {
        ROOM_ITEM_ID_KEY: 801,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_J,
        ROOM_PICK_POSITIONS_KEY: [
            "SILVER KEY LIST 2",
            "LIBRARY LIST",
            "LIBRARY LIST RARER",
            "DOWSING NOMBOS",
            "BLACKPRINTS",
        ],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_KNIGHT,
    },
    "Throne Room": {
        ROOM_ITEM_ID_KEY: 802,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_T,
        ROOM_PICK_POSITIONS_KEY: ["EDGEPIERCE - RARE G", "CENTER - Tier 2 G"],
        OUTER_ROOM_KEY: False,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_KING,
    },
    "Tomb": {
        ROOM_ITEM_ID_KEY: 803,
        ROOM_ITEM_CLASSIFICATION_KEY: ItemClassification.progression,
        ROOM_ITEM_SPOT_COUNT_KEY: 0,
        ROOM_CHEST_SPOT_COUNT_KEY: 0,
        ROOM_LAYOUT_TYPE_KEY: ROOM_LAYOUT_TYPE_D,
        ROOM_PICK_POSITIONS_KEY: ["STANDALONE ARRAY", "STANDALONE ARRAY FULL"],
        OUTER_ROOM_KEY: True,
        ROOM_CHESS_PIECE_KEY: CHESS_PIECE_NONE,
    },
}

rooms = blue_rooms | bedrooms | hallways | green_rooms | shops | red_rooms | black_rooms
